<a href="https://colab.research.google.com/github/Sakshi-HC-Gowda/Data-Science-and-Gen-AI/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
class CSE():
  s1='Sakshi'
  s2='Teja'
  s3='Sanu'
  s4='Sam'
HOD=CSE()

'Sakshi'

In [5]:
CSE.s1

'Sakshi'

In [6]:
HOD.s1

'Sakshi'

In [13]:
class ELECTRONICS():
  def ECE(self):
    print('This is ECE')
  def EEE(self):
    print('This is EEE')
obj=ELECTRONICS()
obj.ECE()
obj.EEE()

This is ECE
This is EEE


In [14]:
#Create a class and execute all the arithmetic operations using different functions

class Arithmetic:

    def add(self, a, b):
        print("Addition =", a + b)

    def sub(self, a, b):
        print("Subtraction =", a - b)

    def mul(self, a, b):
        print("Multiplication =", a * b)

    def div(self, a, b):
        print("Division =", a / b)


obj = Arithmetic()

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

obj.add(a, b)
obj.sub(a, b)
obj.mul(a, b)
obj.div(a, b)

Enter first number: 1
Enter second number: 2
Addition = 3
Subtraction = -1
Multiplication = 2
Division = 0.5


In [15]:
#SINGLE LEVEL INHERITANCE
class PARENT():
  def properties(self):
    print('We have properties')
class CHILD(PARENT):
  def bile(self):
    print('I own a bike')
obj2=CHILD()
obj2.properties()

We have properties


In [16]:
#MULTI LEVEL INHERITANCE
class GRANDPARENT():
  def strength(self):
    print('We stay strong')
class PARENT1(GRANDPARENT):
  def assests(self):
    print('We have assests')

class CHILD2(PARENT1):
  def fun(self):
    print('We have a lot of fun')
obj3=CHILD2()
obj3.strength()

We stay strong


In [21]:

class PARENT2():
  def add(self):
    pass
class PARENT3():
  def sub(self):
    pass

class CHILD3(PARENT2,PARENT3):
  def op(self):
    pass

obj4=CHILD3()
obj4.add()

In [19]:
# HIERARCHICAL INHERITANCE
class PARENT():
    def properties(self):
        print("We have properties")

class CHILD1(PARENT):
    def bike(self):
        print("I own a bike")

class CHILD2(PARENT):
    def car(self):
        print("I own a car")

obj1 = CHILD1()
obj1.properties()
obj1.bike()

obj2 = CHILD2()
obj2.properties()
obj2.car()

We have properties
I own a bike
We have properties
I own a car


In [20]:
# HYBRID INHERITANCE
class GRANDPARENT():
    def strength(self):
        print("We stay strong")

class PARENT1(GRANDPARENT):
    def house(self):
        print("We have a house")

class PARENT2(GRANDPARENT):
    def land(self):
        print("We have land")

class CHILD(PARENT1, PARENT2):
    def bike(self):
        print("I own a bike")

obj = CHILD()
obj.strength()
obj.house()
obj.land()
obj.bike()

We stay strong
We have a house
We have land
I own a bike


In [25]:
#Array
#List and an array
#Dimensional
import numpy as np
a=[10,20,30,40]
print(a)

[10, 20, 30, 40]


In [26]:
nums=np.array([10,20,30,40])
print(nums)

[10 20 30 40]


In [27]:
print(nums*2)

[20 40 60 80]


In [28]:
nums2=np.array([50,60,70,80])
print(nums+nums2)

[ 60  80 100 120]


In [30]:
import numpy as np
prices=np.array([15,25,5,42,19])
#Vectorized conditinal check
expensive=prices>20
print(expensive)

[False  True False  True False]


In [31]:
#Vectorized functions
data=np.array([1,4,9,16,25])
print(np.sqrt(data))

[1. 2. 3. 4. 5.]


In [32]:
print(np.sum(data))

55


In [33]:
data

array([ 1,  4,  9, 16, 25])

In [34]:
print(data[3])

16


In [35]:
print(data[::-1])

[25 16  9  4  1]


In [42]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(matrix[0,:])

[1 2 3]


In [43]:
#Boolean indexing
arr=np.array([10,25,40,55])
print(arr[arr>30])

[40 55]


In [45]:
#Broadcasting

#Scalar Broadcasting
arr2=np.array([1,2,3])
print(arr2+5)

[6 7 8]


In [51]:
#1d to 2d array broadcasting
import numpy as np
x=np.array([[10,20,30],[40,50,60]])
y=np.array([100,200,300])
print(x+y)


[[110 220 330]
 [140 250 360]]


In [46]:
#arange

z=np.arange(1,11)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
#converting 1D array to a 2D array

w=np.arange(1,61)
print(w)
print(w.ndim)
print('---------------------------------')
r=w.reshape(10,6)
print(r)
print(r.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
---------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [50]:
#1D to 3D

u=np.arange(1,61).reshape(5,2,6)
print(u)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [53]:
#Given an array A of shape (3, 3) and a 1D array B of shape (3,), what will be the shape of the resulting array when you add them together (A + B)?
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
B=np.array([10,20,30])
C=A+B
print(C)
print(C.shape)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
(3, 3)


In [57]:
#Consider the 2D array A = np.array([[1, 2], [3, 4], [5, 6]]). What will be the shape of the resulting array if you index it using A[[0, 2]]?
A=np.array([[1,2],
            [3,4],
            [5,6]])
B=A[[0,2]]
print(B)
print(B.shape)


[[1 2]
 [5 6]]
(2, 2)


In [58]:
#Given A = np.array([1, 2, 3, 4, 5]), what does the expression A[A % 2 == 0] evaluate to?
A=np.array([1,2,3,4,5])
A[A%2==0]

array([2, 4])

In [60]:
A = np.arange(9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
