<a href="https://colab.research.google.com/github/Sakshi-HC-Gowda/Data-Science-and-Gen-AI/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


15/07/2026



**SQL**

In [ ]:
pip install ipython-sql

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [ ]:
%sql sqlite://

In [ ]:
%%sql
CREATE TABLE students(
  id INTEGER PRIMARY KEY,
  name TEXT,
  department TEXT,
  age INTEGER,
  marks INTEGER
);

INSERT INTO students VALUES
(1,'Sakshi','cse',22,80),
(2,'Sanu','cse',22,74),
(3,'Gnanu','AI',21,75),
(4,'Janvi','ece',22,78),
(5,'Priya','AI',21,70),
(6,'Reema','ece',22,72);

 * sqlite://
Done.
6 rows affected.


[]

In [ ]:
import pandas as pd
import sqlite3

# Connect to the SQLite database (assuming it's in-memory as per %sql sqlite://)
conn = sqlite3.connect(':memory:')

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute('''
CREATE TABLE students(
  id INTEGER PRIMARY KEY,
  name TEXT,
  department TEXT,
  age INTEGER,
  marks INTEGER
);
''')
cursor.execute('''
INSERT INTO students VALUES
(1,'Sakshi','cse',22,80),
(2,'Sanu','cse',22,74),
(3,'Gnanu','AI',21,75),
(4,'Janvi','ece',22,78),
(5,'Priya','AI',21,70),
(6,'Reema','ece',22,72);
''')
conn.commit()

df = pd.read_sql('SELECT * FROM students', conn)
conn.close()

df

,id,name,department,age,marks
0,1,Sakshi,cse,22,80
1,2,Sanu,cse,22,74
2,3,Gnanu,AI,21,75
3,4,Janvi,ece,22,78
4,5,Priya,AI,21,70
5,6,Reema,ece,22,72


16/07/2026


Machine (Math) Learning from the data is called ML

In [ ]:
import pandas as pd

data = {
    'experience': [1, 3, 5, 7, 10,11,12,13],
    'salary': [13, 14, 15, 16,20,22,23,30]
}
df = pd.DataFrame(data)

df

,experience,salary
0,1,13
1,3,14
2,5,15
3,7,16
4,10,20
5,11,22
6,12,23
7,13,30


In [ ]:
X=df.iloc[:,:-1]
X #Independent feature (left-row, right-column )

,experience
0,1
1,3
2,5
3,7
4,10
5,11
6,12
7,13


In [ ]:
y=df.iloc[:,-1]
y   #dependent feature

,salary
0,13
1,14
2,15
3,16
4,20
5,22
6,23
7,30


In [ ]:
#Machine(Math) Learning
import sklearn

In [ ]:
#Exam - Sunday,Monday-Friday, Sat,Sun
#traing and testing data
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

,experience
0,1
7,13
2,5
4,10
3,7
6,12


In [ ]:
X_test

,experience
1,3
5,11


In [ ]:
y_train

,salary
0,13
7,30
2,15
4,20
3,16
6,23


In [ ]:
y_test

,salary
1,14
5,22


In [ ]:
training_data=pd.DataFrame()
training_data['X_train']=x_train
training_data['y_train']=y_train
training_data

,X_train,y_train
0,1,13
7,13,30
2,5,15
4,10,20
3,7,16
6,12,23


In [ ]:
testing_data=pd.DataFrame()
testing_data['X_train']=x_test
testing_data['y_train']=y_test
testing_data

,X_train,y_train
1,3,14
5,11,22


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression()

In [ ]:
#y=mx+c
reg.fit(X_train,y_train)


LinearRegression()

In [ ]:
reg.coef_ #m_value

array([1.25])

In [ ]:
reg.intercept_ #c_value

np.float64(9.5)

In [ ]:
#y=mx+c
1.25*3+9.5

13.25

In [ ]:
#y=1.25(x)+9.5 This is the model
1.25*5+9.5

15.75

In [ ]:
y_train_predictions=reg.predict(X_train)
training_data

,X_train,y_train
0,1,13
7,13,30
2,5,15
4,10,20
3,7,16
6,12,23


In [ ]:
training_data['y_train_predictions']=y_train_predictions
training_data

,X_train,y_train,y_train_predictions
0,1,13,10.75
7,13,30,25.75
2,5,15,15.75
4,10,20,22.00
3,7,16,18.25
6,12,23,24.50


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Create sample dataset
data = {
    "Experience": [1, 3, 5, 7, 10],
    "Age": [22, 25, 28, 30, 35],
    "Education_Level": [1, 2, 2, 3, 3],
    "Salary": [30000, 45000, 60000, 80000, 120000]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Independent variables
X = df[["Experience", "Age", "Education_Level"]]

# Dependent variable
y = df["Salary"]

# Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)



In [ ]:
X_train,X_test

(   Experience  Age  Education_Level
 4          10   35                3
 2           5   28                2
 0           1   22                1
 3           7   30                3,
    Experience  Age  Education_Level
 1           3   25                2)

In [ ]:
# Create Multiple Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Display coefficients
print("Coefficients:", model.coef_)

# Display intercept
print("Intercept:", model.intercept_)

# Predict salary for test data
prediction = model.predict(X_test)

print("Predicted Salary:", prediction)

In [ ]:
import pandas as pd

data = {
    "Rainfall_mm": [400, 450, 500, 550, 600, 650, 700, 750, 800, 850],
    "Temperature_C": [20, 22, 24, 25, 26, 27, 28, 29, 30, 31],
    "Fertilizer_kg": [30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
    "Soil_pH": [5.8, 6.0, 6.2, 6.4, 6.5, 6.7, 6.8, 7.0, 7.2, 7.4],
    "Crop_Yield": [18, 22, 27, 31, 36, 40, 45, 49, 54, 58]
}

df = pd.DataFrame(data)
print(df)

   Rainfall_mm  Temperature_C  Fertilizer_kg  Soil_pH  Crop_Yield
0          400             20             30      5.8          18
1          450             22             35      6.0          22
2          500             24             40      6.2          27
3          550             25             45      6.4          31
4          600             26             50      6.5          36
5          650             27             55      6.7          40
6          700             28             60      6.8          45
7          750             29             65      7.0          49
8          800             30             70      7.2          54
9          850             31             75      7.4          58


In [ ]:
X = df.iloc[:, 0:4]
X

,Rainfall_mm,Temperature_C,Fertilizer_kg,Soil_pH
0,400,20,30,5.8
1,450,22,35,6.0
2,500,24,40,6.2
3,550,25,45,6.4
4,600,26,50,6.5
5,650,27,55,6.7
6,700,28,60,6.8
7,750,29,65,7.0
8,800,30,70,7.2
9,850,31,75,7.4


In [ ]:
y = df.iloc[:, 4]
y

,Crop_Yield
0,18
1,22
2,27
3,31
4,36
5,40
6,45
7,49
8,54
9,58


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

print("X Train")
print(X_train)

print("\nX Test")
print(X_test)

X Train
   Rainfall_mm  Temperature_C  Fertilizer_kg  Soil_pH
5          650             27             55      6.7
0          400             20             30      5.8
7          750             29             65      7.0
2          500             24             40      6.2
9          850             31             75      7.4
4          600             26             50      6.5
3          550             25             45      6.4
6          700             28             60      6.8

X Test
   Rainfall_mm  Temperature_C  Fertilizer_kg  Soil_pH
8          800             30             70      7.2
1          450             22             35      6.0


In [ ]:

print("\ny Train")
print(y_train)

print("\ny Test")
print(y_test)


y Train
5    40
0    18
7    49
2    27
9    58
4    36
3    31
6    45
Name: Crop_Yield, dtype: int64

y Test
8    54
1    22
Name: Crop_Yield, dtype: int64


In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Train the model using training data
model.fit(X_train, y_train)

# Display coefficients of independent variables
print("Coefficients:", model.coef_)

# Display intercept
print("Intercept:", model.intercept_)

# Predict crop yield for test data
y_pred = model.predict(X_test)

# Display predicted values
print("Predicted Crop Yield:")
print(y_pred)

Coefficients: [ 0.10048766  0.11940299  0.01004877 -4.47761194]
Intercept: 1.085562287572742
Predicted Crop Yield:
[53.52238806 22.41791045]


In [ ]:
#Y=m1​X1​+m2​X2​+m3​X3​+m4​X4​+c
# Compare actual and predicted crop yield
result = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(result)

   Actual  Predicted
8      54  53.522388
1      22  22.417910


In [ ]:
print(model.coef_)
print(model.intercept_)

[ 0.10048766  0.11940299  0.01004877 -4.47761194]
1.085562287572742


In [ ]:
#y = 0.10048766(Rainfall_mm)+ 0.11940299(Temperature_C)+ 0.01004877(Fertilizer_kg)- 4.47761194(Soil_pH)+ 1.08556229

y = 0.10048766 * 650 + 0.11940299 * 27 + 0.01004877 * 55 - 4.47761194 * 6.7 + 1.08556229
y

40.179104372000005

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Re-create the Crop Yield dataset and split for context
data = {
    "Rainfall_mm": [400, 450, 500, 550, 600, 650, 700, 750, 800, 850],
    "Temperature_C": [20, 22, 24, 25, 26, 27, 28, 29, 30, 31],
    "Fertilizer_kg": [30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
    "Soil_pH": [5.8, 6.0, 6.2, 6.4, 6.5, 6.7, 6.8, 7.0, 7.2, 7.4],
    "Crop_Yield": [18, 22, 27, 31, 36, 40, 45, 49, 54, 58]
}
df = pd.DataFrame(data)

X = df.iloc[:, 0:4]
y = df.iloc[:, 4]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the model again to ensure it's defined
model = LinearRegression()
model.fit(X_train, y_train)

# Training accuracy
train_accuracy = model.score(X_train, y_train)

# Testing accuracy
test_accuracy = model.score(X_test, y_test)

print("Training Accuracy (R² Score):", train_accuracy)
print("Testing Accuracy (R² Score):", test_accuracy)

Training Accuracy (R² Score): 0.9998439856466795
Testing Accuracy (R² Score): 0.9992133548674538


In [ ]:
from sklearn.datasets import fetch_lfw_pairs

lfw = fetch_lfw_pairs()

print(lfw.keys())

dict_keys(['data', 'pairs', 'target', 'target_names', 'DESCR'])


In [ ]:
print(lfw.target_names)

['Different persons' 'Same person']


In [ ]:
import pandas as pd

df = pd.DataFrame(lfw.data)
df["Target"] = lfw.target
print(df["Target"].value_counts())

Target
1    1100
0    1100
Name: count, dtype: int64


In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test)

print(y_pred)

[0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0
 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1
 1 1 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0
 0 0 1 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1
 1 1 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 1 1 1
 1 0 1 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 0 1
 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 0 0
 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0
 0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 0 1
 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1
 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0
 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 1 0]


In [ ]:
train_accuracy = model.score(X_train, y_train)

print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.9715909090909091


In [ ]:
test_accuracy = model.score(X_test, y_test)

print("Testing Accuracy:", test_accuracy)

Testing Accuracy: 0.5590909090909091


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[126  87]
 [107 120]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.54      0.59      0.57       213
           1       0.58      0.53      0.55       227

    accuracy                           0.56       440
   macro avg       0.56      0.56      0.56       440
weighted avg       0.56      0.56      0.56       440

