<a href="https://colab.research.google.com/github/Sakshi-HC-Gowda/Data-Science-and-Gen-AI/blob/main/Introduction_to_Gen_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IDE**
(Integrated Development Environment)

In [ ]:
a = 10
b = 20
print(a)

10


In [ ]:
111student = 98
print(111student)

SyntaxError: invalid decimal literal (2277114784.py, line 1)

**Rules for creating a variable**

- Never start your variable name with a number
- Use underscore(_) if you want to use a number at thr begininng
- Never use spaces in your variable name
- If you want to use spaces, use underscore(_)

In [ ]:
_111student = 100
print(_111student)

100


In [ ]:
Full_Name = 'Venkat Sure'
print(Full_Name)

Venkat Sure


In [ ]:
class = 10
print(class)

SyntaxError: invalid syntax (1551882446.py, line 1)

In [ ]:
score = 100
print('score')

score


In [ ]:
print(score)

100


**Data Structures**

- Strings
- Lists
- Tuples
- Set
- Dictionaries

In [ ]:
# Strings - Any text enclosed in between quotation marks

name = 'Abhishek@123'
print(name)
print(type(name))

Abhishek@123
<class 'str'>


**Mutable**
- If we can add,delete or modify the memory space it is called as a mutable data structure

**Immutable**
- If we cannot add,delete or modify the memory space it is called as a mutable data structure

In [ ]:
name = 'Ram'    # n-1 -> 3-1=2
print(name[2])  # Index values

m


In [ ]:
name[2] = 'n'

TypeError: 'str' object does not support item assignment

In [ ]:
del(name[2])

TypeError: 'str' object doesn't support item deletion

**String is a Immutable Data structure**

In [ ]:
# List

names = ['Abhishek','Tejas','Chirashree','Seetharama']
print(type(names))

<class 'list'>


In [ ]:
scores = [99,98.5,97,95.5]
print(type(scores))

<class 'list'>


In [ ]:
names[2] = 'priya'

In [ ]:
print(names)

['Abhishek', 'Tejas', 'priya', 'Seetharama']


In [ ]:
del(names[2])

In [ ]:
print(names)

['Abhishek', 'Tejas', 'Seetharama']


**List is a Mutable Data Structure**

In [ ]:
# Tuple

companies = ('redbus','morgan stanley','Oracle')
print(type(companies))

<class 'tuple'>


In [ ]:
tuple_checking = (100,150.5,'Oracle',[10,20,30])
print(tuple_checking)

(100, 150.5, 'Oracle', [10, 20, 30])


In [ ]:
# Tuple Packing

batches = 'CSE','ECE','DS','AI'
print(batches)
print(type(batches))

('CSE', 'ECE', 'DS', 'AI')
<class 'tuple'>


In [ ]:
batches[3]

'AI'

In [ ]:
batchnums = (10,10,10,20,30,40)
batchnums.count(40)

1

In [ ]:
batchnums[0] = 20

TypeError: 'tuple' object does not support item assignment

In [ ]:
del(batchnums[0])

TypeError: 'tuple' object doesn't support item deletion

**Tuple is a Immutable Data Structure**

In [ ]:
batchnums.index(40)

5

In [ ]:
# Sets

scorecard = {98,98,97,97,99,100}
print(scorecard)

{97, 98, 99, 100}


In [ ]:
x = {100,150,75,55,205,175}
print(x)

{100, 150, 55, 75, 205, 175}


In [ ]:
print(x)

{100, 150, 55, 75, 205, 175}


- Set is an unordered pair
- Set does not store duplicate Values

In [ ]:
x[0]

TypeError: 'set' object is not subscriptable

In [ ]:
y = {10,10.5,'Bhushan',(10,20)}
print(y)

{10, 10.5, 'Bhushan', (10, 20)}


**Set is a Mutable Data Structure**

In [ ]:
y.add(100)

In [ ]:
print(y)

{100, 10, 10.5, (10, 20), 'Bhushan'}


In [ ]:
# Dictionaries

package = {'Bhushan' : 24, 'Tejas' : 25, 'Abhishek' : 26}
print(package)

{'Bhushan': 24, 'Tejas': 25, 'Abhishek': 26}


In [ ]:
package.keys()

dict_keys(['Bhushan', 'Tejas', 'Abhishek'])

In [ ]:
package.values()

dict_values([24, 25, 26])

In [ ]:
package['Abhishek'] = 30

In [ ]:
print(package)

{'Bhushan': 24, 'Tejas': 25, 'Abhishek': 30}


**Dictionary is a mutable data structure**

In [ ]:
# Conditional Statements

attendance = 80

if attendance > 80:
  print('You are eligible')

else:
  print('You are not eligible')

You are not eligible


In [ ]:
attendance = 80

if attendance > 80:
  print('You are eligible')

elif attendance < 80 and attendance > 75:
  print('You will be allowed but with a fine')

else:
  print('You are not eligible')

You are not eligible


In [ ]:
# Control Statements (Loops)

for i in range(1,101):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
for i in range(1,11):
  if i%2 == 0:
    print(f'{i} is Even')
  else:
    print(f'{i} is Odd')

1 is Odd
2 is Even
3 is Odd
4 is Even
5 is Odd
6 is Even
7 is Odd
8 is Even
9 is Odd
10 is Even


In [ ]:
10%2

0

**Functions**

In [ ]:
x = 100
y = 200
print(x+y)

300


In [ ]:
n1 = 1000
n2 = 2000
print(n1+n2)

3000


In [ ]:
# Functions without parameters

def add():
  x = 155
  y = 145
  print(x+y)

In [ ]:
add()

300


In [ ]:
# Function with parameters

def addition(y,z):
  print(y+z)

In [ ]:
addition(178,122)

300


In [ ]:
addition(750,250)

1000


In [ ]:
addition(16,9)

25


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz

In [ ]:
for i in range(1,101):
  if i%15 == 0:
    print('FizzBuzz')
  elif i%3 == 0:
    print('Fizz')
  elif i%5 == 0:
    print('Buzz')
  else:
    print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


**OOPS**

- Classes and Objects
- Inheritance
- Polymorphism

In [ ]:
# OOPS (Object Oriented Programming System)

class CSE():
  s1 = 'Manikanta'
  s2 = 'Sushmitha'
  s3 = 'Tejas'
  s4 = 'Bhushan'

HOD = CSE()
HOD.s1

'Manikanta'

In [ ]:
CSE.s1

'Manikanta'

In [ ]:
HOD.s1 = 'Ashish'

In [ ]:
CSE.s1

'Manikanta'

In [ ]:
HOD.s1

'Ashish'

In [ ]:
class ELECTRONICS():
  def ECE(self):
    print('This is ECE')
  def EEE(self):
    print('This is EEE')

obj = ELECTRONICS()
obj.EEE()

This is EEE


- Create a class and execute all the arithemetic operations using different functions

In [ ]:
# Inheritance

class PARENT():
  def properties(self):
    print('We have properties')

class CHILD(PARENT):
  def bike(self):
    print('I own a bike')

obj2 = CHILD()
obj2.properties()

We have properties


In [ ]:
# Multi level Inheritance

class GRANDPARENT():
  def strength(self):
    print('We stay strong')

class PARENT1(GRANDPARENT):
  def assets(self):
    print('We have assets')

class CHILD2(PARENT1):
  def fun(self):
    print('We have a lot of fun')


obj3 = CHILD2()
obj3.strength()

We stay strong


In [ ]:
class PARENT2():
  def add(self):
    pass

class PARENT3():
  def sub(self):
    pass

class CHILD3(PARENT2,PARENT3):
  def op(self):
    pass


obj4 = CHILD3()
obj4.add()

**LIBRARIES**
- Numpy
- Pandas
- Matplotlib

In [ ]:
# Numpy - Numerical Python

import numpy as np

In [ ]:
len(dir(np))

533

In [ ]:
# Array

# list and an array

# Dimensional

a = [10,20,30,40]
print(a)

[10, 20, 30, 40]


In [ ]:
nums = np.array([10,20,30,40])
print(nums)

[10 20 30 40]


In [ ]:
print(nums*2)

[20 40 60 80]


In [ ]:
nums2 = np.array([50,60,70,80])
print(nums+nums2)


[ 60  80 100 120]


In [ ]:
prices = np.array([15,25,5,42,19])

# Vectorized conditional check

expensive = prices>20
print(expensive)

[False  True False  True False]


In [ ]:
# Vectorized functions

data = np.array([1,4,9,16,25])

print(np.sqrt(data))

[1. 2. 3. 4. 5.]


In [ ]:
# Vectorized aggregation

print(np.sum(data))

55


In [ ]:
data

array([ 1,  4,  9, 16, 25])

In [ ]:
print(data[3])

16


In [ ]:
print(data[1:4])

[ 4  9 16]


In [ ]:
print(data[::-1])

[25 16  9  4  1]


In [ ]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(matrix[1,:])

[4 5 6]


In [ ]:
# Boolean Filtering

arr = np.array([10,25,40,55])
print(arr[arr>30])

[40 55]


In [ ]:
# Broadcasting

# Scalar Broadcasting

arr2 = np.array([1,2,3])
print(arr2+5)

[6 7 8]


In [ ]:
# 1D to 2D Array Broadcasting

x = np.array([[10,20,30],
              [40,50,60]])

y = np.array([100,200,300])

print(x+y)

[[110 220 330]
 [140 250 360]]


In [ ]:
print(y.shape)
print(y.ndim)
print(y.size)

(3,)
1
3


In [ ]:
# arange

z = np.arange(1,11)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# converting 1D array to a 2D array

w = np.arange(1,61)
print(w)
print(w.ndim)
print('-----------------------------------------------------------------')

r = w.reshape(12,5)
print(r)
print(r.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
-----------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]
2


In [ ]:
t = np.arange(1,101).reshape(10,10)
print(t)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
# 1D to 3D

u = np.arange(1,61).reshape(5,2,6)
print(u)
print(u.ndim)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
